version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: fitness_postgres
    environment:
      POSTGRES_USER: vishnu
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: fitness
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: fitness_redis
    ports:
      - '6379:6379'
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local